<h1>This is my template, there are many like it, but this one is mine.</h1>

<ol>
	<?php 
		/*$array = $block->setFilms();
		foreach ($array as $value) { */?>
			<li><?php /*echo $value */?></li>
		<?php/* } */?>		
</ol>

<ol>
	<?php 
		$array = $block->setFilms();
		$count = 1;
		foreach ($array as $value) { ?>
			<li><a href="<?= $block->getUrl('demo/show/' , ['title' => 'id'.$count.'']) ?>"><?php echo $value ?></a>
			</li>
		<?php $count++;
		} ?>		
</ol>
